site_name: Python Liquid
site_description: A Python engine for the Liquid template language.

theme:
  name: "material"
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
  features:
    - navigation.sections
    - content.code.copy
  logo: img/droplet_white_liquid.svg
  favicon: img/favicon.ico
  custom_dir: docs/.overrides

repo_name: jg-rp/liquid
repo_url: https://github.com/jg-rp/liquid
edit_uri: ""

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 2
            show_source: false
            show_signature_annotations: true
            show_root_heading: true
            separate_signature: true
            docstring_section_style: "spacy"
            merge_init_into_class: true
            show_root_full_path: false
  - autorefs

nav:
  - Introduction: "index.md"
  - API Reference:
      - Rendering Templates: "api.md"
      - Template Analysis: "analysis.md"
      - Template Loaders: "loaders.md"
      - Undefined Types: "undefined.md"
      - Exceptions: "exceptions.md"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - css/style.css

watch:
  - liquid
