[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "python-liquid"
description = "A Python engine for the Liquid template language."
dynamic = ["version"]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"

authors = [{ name = "James Prior", email = "jamesgr.prior@gmail.com" }]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
]

dependencies = [
  "MarkupSafe>=3",
  "python-dateutil>=2.8.1",
  "Babel>=2",
  "pytz",
]

[project.urls]
"Change Log" = "https://github.com/jg-rp/liquid/blob/main/CHANGES.md"
Documentation = "https://jg-rp.github.io/liquid/"
Homepage = "https://jg-rp.github.io/liquid/"
"Issue Tracker" = "https://github.com/jg-rp/liquid/issues"
"Source Code" = "https://github.com/jg-rp/liquid"

[tool.hatch.version]
path = "src/python_liquid/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "furo",
  "ghp-import",
  "hypothesis",
  "pygments-liquid2",
  "pytest",
  "pytest-cov",
  "pytest-mock",
  "pytest-timeout",
  "pyperf>=2.10.0",
  "mypy",
  "pyyaml",
  "types-pyyaml",
  "twine",
  "ruff",
  "mock",
  "sphinx>=9.1.0",
  "sphinx_copybutton",
  "types-python-dateutil",
  "types-mock",
  "types-pytz",
  "types-babel",
]

[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-fail-under=95 --cov-config=pyproject.toml --cov=src --cov=tests {args}"
benchmark = "python -O scripts/performance.py"
cov-html = "pytest --cov-report=html --cov-config=pyproject.toml --cov=liquid --cov=tests {args}"
lint = "ruff check ."
no-cov = "cov --no-cov {args}"
profile = "python -O scripts/performance.py --profile"
test = "pytest {args}"
typing = "mypy"

[[tool.hatch.envs.test.matrix]]
python = ["312", "313", "314"]

[tool.coverage.run]
branch = true
omit = ["tests/mocks/**/*", "src/python_liquid/__about__.py"]
parallel = true

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]

[tool.mypy]
python_version = "3.12"
strict = true
