/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebar: [
    {
      type: "category",
      label: "Introduction",
      collapsed: false,
      items: [
        "introduction/getting-started",
        "introduction/loading-templates",
        "introduction/render-context",
        "introduction/objects-and-drops",
        "introduction/strictness",
        "introduction/auto-escape",
        "introduction/async-support",
      ]
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "guides/custom-filters",
        "guides/custom-tags",
        "guides/custom-loaders",
        "guides/custom-template-cache",
      ]
    }
  ],

  languageSidebar: [
    {
      type: "category",
      label: "Language",
      collapsed: false,
      items: [
        "language/introduction",
        "language/filters",
        "language/tags",
      ]
    },
    {
      type: "category",
      label: "Extra",
      collapsed: false,
      items: [
        "extra/introduction",
        "extra/filters",
        "extra/tags",
      ]
    }
  ],

  apiSidebar: [
    {
      type: "category",
      label: "API",
      collapsed: false,
      items: [
        "api/Template",
        "api/Environment",
        "api/BoundTemplate",
        "api/filesystemloader",
        "api/choiceloader",
        "api/dictloader",
        "api/context",
        "api/Tag",
        "api/node",
        "api/exceptions",
      ]
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
