# flake8: noqa

from typing import Any
from typing import Iterator
from typing import MutableMapping

class LRUCache(MutableMapping[Any, Any]):
    def __init__(self, capacity: int) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def copy(self) -> LRUCache: ...
    def __reversed__(self) -> Iterator[Any]: ...
