# DO NOT EDIT -- generated by generate_tokens.py

from typing import Literal

__all__ = (
    "TOKEN_ADD",
    "TOKEN_AND",
    "TOKEN_ARROW",
    "TOKEN_AS",
    "TOKEN_ASSIGN",
    "TOKEN_BLANK",
    "TOKEN_COLON",
    "TOKEN_COMMA",
    "TOKEN_COMMENT",
    "TOKEN_COMMENT_END",
    "TOKEN_COMMENT_START",
    "TOKEN_CONTAINS",
    "TOKEN_DIV",
    "TOKEN_DOT",
    "TOKEN_DOUBLE_DOT",
    "TOKEN_DOUBLE_ESCAPED",
    "TOKEN_DOUBLE_QUOTE",
    "TOKEN_DOUBLE_QUOTED",
    "TOKEN_ELSE",
    "TOKEN_EMPTY",
    "TOKEN_EOI",
    "TOKEN_EQ",
    "TOKEN_FALSE",
    "TOKEN_FLOAT",
    "TOKEN_FOR",
    "TOKEN_GE",
    "TOKEN_GT",
    "TOKEN_HASH",
    "TOKEN_IDENT",
    "TOKEN_IF",
    "TOKEN_IN",
    "TOKEN_INT",
    "TOKEN_INTERPOLATION_END",
    "TOKEN_INTERPOLATION_START",
    "TOKEN_LBRACE",
    "TOKEN_LBRACKET",
    "TOKEN_LE",
    "TOKEN_LPAREN",
    "TOKEN_LT",
    "TOKEN_MOD",
    "TOKEN_MUL",
    "TOKEN_NE",
    "TOKEN_NIL",
    "TOKEN_NOT",
    "TOKEN_NULL",
    "TOKEN_OR",
    "TOKEN_OR_ELSE",
    "TOKEN_OUT_END",
    "TOKEN_OUT_START",
    "TOKEN_PIPE",
    "TOKEN_QUESTION",
    "TOKEN_RBRACE",
    "TOKEN_RBRACKET",
    "TOKEN_RPAREN",
    "TOKEN_SINGLE_ESCAPED",
    "TOKEN_SINGLE_QUOTE",
    "TOKEN_SINGLE_QUOTED",
    "TOKEN_SPAN",
    "TOKEN_SUB",
    "TOKEN_TAG_END",
    "TOKEN_TAG_NAME",
    "TOKEN_TAG_START",
    "TOKEN_TEXT",
    "TOKEN_TRIPLE_DOT",
    "TOKEN_TRUE",
    "TOKEN_UNKNOWN",
    "TOKEN_WC",
    "TOKEN_WITH",
)

type TokenKind = Literal[
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
]

type Token = tuple[TokenKind, int, int]
"""Token type, start index and end index."""

TOKEN_ADD: Literal[1] = 1
TOKEN_AND: Literal[2] = 2
TOKEN_ARROW: Literal[3] = 3
TOKEN_AS: Literal[4] = 4
TOKEN_ASSIGN: Literal[5] = 5
TOKEN_BLANK: Literal[6] = 6
TOKEN_COLON: Literal[7] = 7
TOKEN_COMMA: Literal[8] = 8
TOKEN_COMMENT_END: Literal[9] = 9
TOKEN_COMMENT_START: Literal[10] = 10
TOKEN_COMMENT: Literal[11] = 11
TOKEN_CONTAINS: Literal[12] = 12
TOKEN_DIV: Literal[13] = 13
TOKEN_DOT: Literal[14] = 14
TOKEN_DOUBLE_DOT: Literal[15] = 15
TOKEN_DOUBLE_ESCAPED: Literal[16] = 16
TOKEN_DOUBLE_QUOTE: Literal[17] = 17
TOKEN_DOUBLE_QUOTED: Literal[18] = 18
TOKEN_ELSE: Literal[19] = 19
TOKEN_EMPTY: Literal[20] = 20
TOKEN_EOI: Literal[21] = 21
TOKEN_EQ: Literal[22] = 22
TOKEN_FALSE: Literal[23] = 23
TOKEN_FLOAT: Literal[24] = 24
TOKEN_FOR: Literal[25] = 25
TOKEN_GE: Literal[26] = 26
TOKEN_GT: Literal[27] = 27
TOKEN_HASH: Literal[28] = 28
TOKEN_IDENT: Literal[29] = 29
TOKEN_IF: Literal[30] = 30
TOKEN_IN: Literal[31] = 31
TOKEN_INT: Literal[32] = 32
TOKEN_INTERPOLATION_END: Literal[33] = 33
TOKEN_INTERPOLATION_START: Literal[34] = 34
TOKEN_LBRACE: Literal[35] = 35
TOKEN_LBRACKET: Literal[36] = 36
TOKEN_LE: Literal[37] = 37
TOKEN_LPAREN: Literal[38] = 38
TOKEN_LT: Literal[39] = 39
TOKEN_MOD: Literal[40] = 40
TOKEN_MUL: Literal[41] = 41
TOKEN_NE: Literal[42] = 42
TOKEN_NIL: Literal[43] = 43
TOKEN_NOT: Literal[44] = 44
TOKEN_NULL: Literal[45] = 45
TOKEN_OR_ELSE: Literal[46] = 46
TOKEN_OR: Literal[47] = 47
TOKEN_OUT_END: Literal[48] = 48
TOKEN_OUT_START: Literal[49] = 49
TOKEN_PIPE: Literal[50] = 50
TOKEN_QUESTION: Literal[51] = 51
TOKEN_RBRACE: Literal[52] = 52
TOKEN_RBRACKET: Literal[53] = 53
TOKEN_RPAREN: Literal[54] = 54
TOKEN_SINGLE_ESCAPED: Literal[55] = 55
TOKEN_SINGLE_QUOTE: Literal[56] = 56
TOKEN_SINGLE_QUOTED: Literal[57] = 57
TOKEN_SPAN: Literal[58] = 58
TOKEN_SUB: Literal[59] = 59
TOKEN_TAG_END: Literal[60] = 60
TOKEN_TAG_NAME: Literal[61] = 61
TOKEN_TAG_START: Literal[62] = 62
TOKEN_TEXT: Literal[63] = 63
TOKEN_TRIPLE_DOT: Literal[64] = 64
TOKEN_TRUE: Literal[65] = 65
TOKEN_UNKNOWN: Literal[66] = 66
TOKEN_WC: Literal[67] = 67
TOKEN_WITH: Literal[68] = 68

TOKEN_NAMES = (
    None,
    "ADD",
    "AND",
    "ARROW",
    "AS",
    "ASSIGN",
    "BLANK",
    "COLON",
    "COMMA",
    "COMMENT_END",
    "COMMENT_START",
    "COMMENT",
    "CONTAINS",
    "DIV",
    "DOT",
    "DOUBLE_DOT",
    "DOUBLE_ESCAPED",
    "DOUBLE_QUOTE",
    "DOUBLE_QUOTED",
    "ELSE",
    "EMPTY",
    "EOI",
    "EQ",
    "FALSE",
    "FLOAT",
    "FOR",
    "GE",
    "GT",
    "HASH",
    "IDENT",
    "IF",
    "IN",
    "INT",
    "INTERPOLATION_END",
    "INTERPOLATION_START",
    "LBRACE",
    "LBRACKET",
    "LE",
    "LPAREN",
    "LT",
    "MOD",
    "MUL",
    "NE",
    "NIL",
    "NOT",
    "NULL",
    "OR_ELSE",
    "OR",
    "OUT_END",
    "OUT_START",
    "PIPE",
    "QUESTION",
    "RBRACE",
    "RBRACKET",
    "RPAREN",
    "SINGLE_ESCAPED",
    "SINGLE_QUOTE",
    "SINGLE_QUOTED",
    "SPAN",
    "SUB",
    "TAG_END",
    "TAG_NAME",
    "TAG_START",
    "TEXT",
    "TRIPLE_DOT",
    "TRUE",
    "UNKNOWN",
    "WC",
    "WITH",
)

TOKEN_MAP = {
    TOKEN_ADD: "TOKEN_ADD",
    TOKEN_AND: "TOKEN_AND",
    TOKEN_ARROW: "TOKEN_ARROW",
    TOKEN_AS: "TOKEN_AS",
    TOKEN_ASSIGN: "TOKEN_ASSIGN",
    TOKEN_BLANK: "TOKEN_BLANK",
    TOKEN_COLON: "TOKEN_COLON",
    TOKEN_COMMA: "TOKEN_COMMA",
    TOKEN_COMMENT_END: "TOKEN_COMMENT_END",
    TOKEN_COMMENT_START: "TOKEN_COMMENT_START",
    TOKEN_COMMENT: "TOKEN_COMMENT",
    TOKEN_CONTAINS: "TOKEN_CONTAINS",
    TOKEN_DIV: "TOKEN_DIV",
    TOKEN_DOT: "TOKEN_DOT",
    TOKEN_DOUBLE_DOT: "TOKEN_DOUBLE_DOT",
    TOKEN_DOUBLE_ESCAPED: "TOKEN_DOUBLE_ESCAPED",
    TOKEN_DOUBLE_QUOTE: "TOKEN_DOUBLE_QUOTE",
    TOKEN_DOUBLE_QUOTED: "TOKEN_DOUBLE_QUOTED",
    TOKEN_ELSE: "TOKEN_ELSE",
    TOKEN_EMPTY: "TOKEN_EMPTY",
    TOKEN_EOI: "TOKEN_EOI",
    TOKEN_EQ: "TOKEN_EQ",
    TOKEN_FALSE: "TOKEN_FALSE",
    TOKEN_FLOAT: "TOKEN_FLOAT",
    TOKEN_FOR: "TOKEN_FOR",
    TOKEN_GE: "TOKEN_GE",
    TOKEN_GT: "TOKEN_GT",
    TOKEN_HASH: "TOKEN_HASH",
    TOKEN_IDENT: "TOKEN_IDENT",
    TOKEN_IF: "TOKEN_IF",
    TOKEN_IN: "TOKEN_IN",
    TOKEN_INT: "TOKEN_INT",
    TOKEN_INTERPOLATION_END: "TOKEN_INTERPOLATION_END",
    TOKEN_INTERPOLATION_START: "TOKEN_INTERPOLATION_START",
    TOKEN_LBRACE: "TOKEN_LBRACE",
    TOKEN_LBRACKET: "TOKEN_LBRACKET",
    TOKEN_LE: "TOKEN_LE",
    TOKEN_LPAREN: "TOKEN_LPAREN",
    TOKEN_LT: "TOKEN_LT",
    TOKEN_MOD: "TOKEN_MOD",
    TOKEN_MUL: "TOKEN_MUL",
    TOKEN_NE: "TOKEN_NE",
    TOKEN_NIL: "TOKEN_NIL",
    TOKEN_NOT: "TOKEN_NOT",
    TOKEN_NULL: "TOKEN_NULL",
    TOKEN_OR_ELSE: "TOKEN_OR_ELSE",
    TOKEN_OR: "TOKEN_OR",
    TOKEN_OUT_END: "TOKEN_OUT_END",
    TOKEN_OUT_START: "TOKEN_OUT_START",
    TOKEN_PIPE: "TOKEN_PIPE",
    TOKEN_QUESTION: "TOKEN_QUESTION",
    TOKEN_RBRACE: "TOKEN_RBRACE",
    TOKEN_RBRACKET: "TOKEN_RBRACKET",
    TOKEN_RPAREN: "TOKEN_RPAREN",
    TOKEN_SINGLE_ESCAPED: "TOKEN_SINGLE_ESCAPED",
    TOKEN_SINGLE_QUOTE: "TOKEN_SINGLE_QUOTE",
    TOKEN_SINGLE_QUOTED: "TOKEN_SINGLE_QUOTED",
    TOKEN_SPAN: "TOKEN_SPAN",
    TOKEN_SUB: "TOKEN_SUB",
    TOKEN_TAG_END: "TOKEN_TAG_END",
    TOKEN_TAG_NAME: "TOKEN_TAG_NAME",
    TOKEN_TAG_START: "TOKEN_TAG_START",
    TOKEN_TEXT: "TOKEN_TEXT",
    TOKEN_TRIPLE_DOT: "TOKEN_TRIPLE_DOT",
    TOKEN_TRUE: "TOKEN_TRUE",
    TOKEN_UNKNOWN: "TOKEN_UNKNOWN",
    TOKEN_WC: "TOKEN_WC",
    TOKEN_WITH: "TOKEN_WITH",
}


def token_value(token: Token, source: str) -> str:
    """Return the substring in source spanned by token."""
    return source[token[1] : token[2]]


def span(start: Token, stop: Token) -> Token:
    """Return a new token spanning start and stop."""
    return (TOKEN_SPAN, start[1], stop[2])
