# TODO: pretty names

TOKEN_DEFINITIONS = {
    "ADD": "ADD",
    "AND": "AND",
    "ARROW": "ARROW",
    "AS": "AS",
    "ASSIGN": "ASSIGN",
    "BLANK": "BLANK",
    "COLON": "COLON",
    "COMMA": "COMMA",
    "COMMENT_END": "COMMENT_END",
    "COMMENT_START": "COMMENT_START",
    "COMMENT": "COMMENT",
    "CONTAINS": "CONTAINS",
    "DIV": "DIV",
    "DOT": "DOT",
    "DOUBLE_DOT": "DOUBLE_DOT",
    "DOUBLE_ESCAPED": "DOUBLE_ESCAPED",
    "DOUBLE_QUOTE": "DOUBLE_QUOTE",
    "DOUBLE_QUOTED": "DOUBLE_QUOTED",
    "ELSE": "ELSE",
    "EMPTY": "EMPTY",
    "EOI": "EOI",
    "EQ": "EQ",
    "FALSE": "FALSE",
    "FLOAT": "FLOAT",
    "FOR": "FOR",
    "GE": "GE",
    "GT": "GT",
    "HASH": "HASH",
    "IDENT": "IDENT",
    "IF": "IF",
    "IN": "IN",
    "INT": "INT",
    "INTERPOLATION_END": "INTERPOLATION_END",
    "INTERPOLATION_START": "INTERPOLATION_START",
    "LBRACE": "LBRACE",
    "LBRACKET": "LBRACKET",
    "LE": "LE",
    "LPAREN": "LPAREN",
    "LT": "LT",
    "MOD": "MOD",
    "MUL": "MUL",
    "NE": "NE",
    "NIL": "NIL",
    "NOT": "NOT",
    "NULL": "NULL",
    "OR_ELSE": "OR_ELSE",
    "OR": "OR",
    "OUT_END": "OUT_END",
    "OUT_START": "OUT_START",
    "PIPE": "PIPE",
    "QUESTION": "QUESTION",
    "RBRACE": "RBRACE",
    "RBRACKET": "RBRACKET",
    "RPAREN": "RPAREN",
    "SINGLE_ESCAPED": "SINGLE_ESCAPED",
    "SINGLE_QUOTE": "SINGLE_QUOTE",
    "SINGLE_QUOTED": "SINGLE_QUOTED",
    "SPAN": "SPAN",
    "SUB": "SUB",
    "TAG_END": "TAG_END",
    "TAG_NAME": "TAG_NAME",
    "TAG_START": "TAG_START",
    "TEXT": "TEXT",
    "TRIPLE_DOT": "TRIPLE_DOT",
    "TRUE": "TRUE",
    "UNKNOWN": "UNKNOWN",
    "WC": "WC",
    "WITH": "WITH",
}


def generate() -> str:
    constants: list[str] = []
    names: list[str] = []
    literals: list[str] = []
    mapping: list[str] = []

    for id, (name, description) in enumerate(TOKEN_DEFINITIONS.items(), 1):
        constant = f"TOKEN_{name}"

        constants.append(f"{constant}: Literal[{id}] = {id}")
        names.append(f"    {constant!r}: {description!r}")
        literals.append(f"    {id}")
        mapping.append(f"    {constant}: {constant!r}")

    return f"""\
# DO NOT EDIT -- generated by generate_tokens.py

from typing import Literal

__all__ = (
{",\n".join(f'    "TOKEN_{name}"' for name in TOKEN_DEFINITIONS)},
)

type TokenKind = Literal[\n{",\n".join(literals)},\n]

type Token = tuple[TokenKind, int, int]
\"\"\"Token type, start index and end index.\"\"\"

{chr(10).join(constants)}

TOKEN_NAMES = (
    None,
{chr(10).join(f"    {description!r}," for description in TOKEN_DEFINITIONS.values())}
)

TOKEN_MAP = {{
{",\n".join(mapping)},
}}


def token_value(token: Token, source: str) -> str:
    \"\"\"Return the substring in source spanned by token.\"\"\"
    return source[token[1] : token[2]]


def span(start: Token, stop: Token) -> Token:
    \"\"\"Return a new token spanning start and stop.\"\"\"
    return (TOKEN_SPAN, start[1], stop[2])
"""


if __name__ == "__main__":
    print(generate())
